spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jeferRestaurantes
    username: jeferRestaurantes
    password: jeferRestaurantes
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQLDialect
      generate-ddl: true
    show-sql: true 